application: zoombeedo
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: index.html
  upload: index\.html

- url: /guia
  static_files: guia.html
  upload: guia\.html

- url: /login
  static_files: login.html
  upload: login\.html

- url: /politicas
  static_files: politicas.html
  upload: politicas\.html

- url: /bootstrap\.css
  static_files: bootstrap.css
  upload: bootstrap\.css
  
- url: /images
  static_dir: images
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /lib
  static_dir: lib
  
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: favicon\.ico